# Site settings
title: Critical Truth
email: fearsometruth@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.critical-truth.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  bentsea

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
encoding: utf-8

paginate: 9
paginate_path: "/reviews/page:num/"
categories: [reviews, editorials, movies, books, games]

sass:
  style: compressed
