# Site settings
title: Critical Truth
email: fearsometruth@gmail.com
description: >
  A home for critical and honest reviews that strive for a
  thoughtful exploration of all forms of art and expression, especially reviews of movies,
  music, TV, and games!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.critical-truth.com" # the base hostname & protocol for your site
twitter_username:
github_username:  bentsea

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
encoding: utf-8
permalink: /articles/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      robots_index: True
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      robots_index: True
      layout: post



# Includes and Excludes
include: [.htaccess,_pages]
exclude: [ps.sh,getInfo.sh,new_post.py]

#Blank array for use in site.
array: []

#Gems
#gems: [octopress-paginate]


categories: [reviews, editorials, movies, books, games, comics, horror, comedy, drama]

sass:
  style: compressed
  
