# Site settings
title: Critical Truth
email: fearsometruth@gmail.com
description: >
  A home for critical and honest reviews that strive for a
  thoughtful exploration of all forms of art and expression, especially reviews of movies,
  music, TV, and games!
baseurl: "" # the subpath of your site, e.g. /blog/
cdnurl: "https://img.critical-truth.com"
url: "https://www.critical-truth.com" # the base hostname & protocol for your site
twitter_username:
github_username:  bentsea

#App Properties
fbappid: 969503389844347

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
encoding: utf-8
permalink: /articles/:year/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      robots_index: True
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      robots_index: True
      layout: post

related:
  max_count: 7


# Includes and Excludes
include: [.htaccess,_pages]
exclude: [ps.sh,getInfo.sh,new_post.py,Gemfile,Gemfile.lock]

#Blank array for use in site.
array: []

#Gems
gems: [octopress-paginate]


categories: [review,editorial,movie,book,game]

sass:
  style: compressed
  
